domain: hundertzehn.github.io
title: MOCO API docs
description: mocoapp.com REST API documentation
remote_theme: just-the-docs/just-the-docs

url: https://hundertzehn.github.io
baseurl: /mocoapp-api-docs

color_scheme: moco

aux_links: # remove if you don't want this link to appear on your pages
  Github: https://github.com/hundertzehn/mocoapp-api-docs
heading_anchors: true
kramdown:
  toc_levels: "2,3"

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: yellow

plugins:
  - jekyll-default-layout

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/hundertzehn/mocoapp-api-docs" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
